/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CreditNoteStatus = "approved_auto" | "approved_manual" | "pending";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LanguagePreference = "de" | "en" | "es" | "it" | "tr";

export type NotificationPreference = "both" | "email" | "sms";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "confirmed" | "delivered" | "delivering" | "pending";

export type PaymentMethodType = "apple_pay" | "credit_card" | "gpay" | "klarna" | "paypal" | "points";

export type PointTransactionType = "admin_adjustment" | "bibercode_credit" | "order_payment" | "topup";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "driver" | "user";

export interface AnalyticsDaily {
  avgDurationSeconds: Generated<Numeric>;
  date: Timestamp;
  id: Generated<number>;
  pagePath: string;
  pageVisits: Generated<number>;
  tabClicks: Generated<number>;
  topTabs: Generated<Json | null>;
  totalDurationSeconds: Generated<number>;
  uniqueSessions: Generated<number>;
}

export interface AnalyticsEvents {
  createdAt: Generated<Timestamp>;
  durationSeconds: number | null;
  eventType: string;
  id: Generated<number>;
  pagePath: string;
  sessionId: string;
  tabName: string | null;
}

export interface AppSettings {
  bonusTiers: Generated<Json | null>;
  contactFromEmail: Generated<string | null>;
  contactFromName: Generated<string | null>;
  contactToEmail: Generated<string | null>;
  contactToName: Generated<string | null>;
  defaultLanguage: Generated<LanguagePreference | null>;
  deliveryDays: Generated<Json | null>;
  deliveryFee: Generated<Numeric | null>;
  deliveryTimeWindow: Generated<string | null>;
  enabledLanguages: Generated<Json | null>;
  facebookUrl: string | null;
  freeDeliveryThreshold: Generated<Numeric | null>;
  id: Generated<number>;
  instagramUrl: string | null;
  microsoftConnectedEmail: string | null;
  openingHours: Generated<Json | null>;
  orderCutoffTime: Generated<string | null>;
  shopLatitude: Generated<Numeric | null>;
  shopLocation: Generated<string | null>;
  shopLongitude: Generated<Numeric | null>;
  tiktokUrl: string | null;
  updatedAt: Generated<Timestamp | null>;
  whatsappNumber: string | null;
  youtubeUrl: string | null;
}

export interface CharityOrganizations {
  active: Generated<boolean>;
  bankDetails: string | null;
  city: string | null;
  contactPerson: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  email: string | null;
  id: Generated<number>;
  logoUrl: string | null;
  name: string;
  phone: string | null;
  postcode: string | null;
  registerNumber: string | null;
  streetAddress: string | null;
  totalPointsEarned: Generated<Numeric>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DeliveryZones {
  activationThreshold: Generated<number | null>;
  active: Generated<boolean | null>;
  cityName: string | null;
  createdAt: Generated<Timestamp | null>;
  deliveryFee: Generated<Numeric | null>;
  id: Generated<number>;
  minimumOrderValue: Generated<Numeric | null>;
  population: number | null;
  postcodePattern: string;
}

export interface DriverCreditNotes {
  approvedAt: Timestamp | null;
  blockEnd: Timestamp;
  blockStart: Timestamp;
  createdAt: Generated<Timestamp>;
  createdByAdminId: number | null;
  detailData: Json | null;
  driverId: number;
  expiresAt: Timestamp;
  gutschriftNumber: string;
  id: Generated<number>;
  packagingCompensation: Generated<Numeric>;
  status: Generated<CreditNoteStatus>;
  stopCompensation: Generated<Numeric>;
  totalAmount: Generated<Numeric>;
  totalPackagingEarnings: Generated<Numeric>;
  totalStopEarnings: Generated<Numeric>;
  vatAmount: Numeric | null;
}

export interface DriverDeliveryRatings {
  cleanRating: number;
  createdAt: Generated<Timestamp>;
  customerId: number;
  driverId: number;
  id: Generated<number>;
  noiseRating: number;
  orderId: number;
  placementRating: number;
}

export interface DriverTips {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  customerId: number;
  driverId: number;
  id: Generated<number>;
  orderId: number;
}

export interface EmailSignatures {
  content: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface EmailTemplates {
  availableVariables: Generated<string>;
  description: string | null;
  htmlBody: string;
  id: Generated<number>;
  name: string;
  slug: string;
  subject: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface NotificationTemplates {
  body: Generated<string>;
  id: Generated<number>;
  lastEdited: Generated<Timestamp | null>;
  subject: string | null;
  templateType: string;
}

export interface OauthAccessToken {
  accessExpiresAt: Timestamp;
  accessToken: string;
  email: string;
  provider: string;
  scopes: string[];
  updatedAt: Generated<Timestamp>;
}

export interface OrderItems {
  id: Generated<number>;
  orderId: number | null;
  productId: number | null;
  productName: string;
  quantity: Generated<number>;
  taxRate: Generated<Numeric | null>;
  unitPrice: Numeric;
}

export interface Orders {
  bibercodePointsCredited: Generated<Numeric | null>;
  createdAt: Generated<Timestamp | null>;
  customerId: number | null;
  deliveryDate: Timestamp | null;
  deliveryDriverId: number | null;
  deliveryFee: Generated<Numeric | null>;
  deliveryNote: string | null;
  deliveryZoneId: number | null;
  id: Generated<number>;
  modified: Generated<boolean>;
  orderDate: Generated<Timestamp | null>;
  orderNumber: string;
  packerDriverId: number | null;
  paymentMethod: PaymentMethodType | null;
  pointsEarned: Generated<Numeric | null>;
  pointsUsed: Generated<Numeric | null>;
  preferredDeliveryDay: Generated<string | null>;
  status: Generated<OrderStatus | null>;
  subtotal: Generated<Numeric | null>;
  total: Generated<Numeric | null>;
}

export interface PasswordResetTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  token: string;
  used: Generated<boolean>;
  userId: number;
}

export interface PointTransactions {
  amount: Numeric;
  createdAt: Generated<Timestamp | null>;
  customerId: number | null;
  id: Generated<number>;
  note: string | null;
  referenceId: string | null;
  type: PointTransactionType;
}

export interface ProductCategories {
  active: Generated<boolean | null>;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
  nameEn: string | null;
  nameEs: string | null;
  nameIt: string | null;
  nameTr: string | null;
  photoUrl: string | null;
  sortOrder: Generated<number | null>;
}

export interface ProductRatings {
  customerId: number | null;
  id: Generated<number>;
  priceRating: number;
  productId: number | null;
  qualityRating: number;
  submittedAt: Generated<Timestamp | null>;
  tasteRating: number;
}

export interface Products {
  active: Generated<boolean | null>;
  articleNumber: string;
  categoryId: number | null;
  compressedPhotoSizeBytes: number | null;
  costPriceEuro: Numeric | null;
  costPriceEuro2: Generated<Numeric | null>;
  costPriceEuro3: Generated<Numeric | null>;
  costPricePercent: Numeric | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  externalUrl: string | null;
  id: Generated<number>;
  isBio: Generated<boolean>;
  isGlutenFree: Generated<boolean>;
  isNew: Generated<boolean>;
  isVegan: Generated<boolean>;
  isVegetarian: Generated<boolean>;
  name: string;
  newDurationDays: number | null;
  newMarkedAt: Timestamp | null;
  originalPhotoSizeBytes: number | null;
  photoUrl: string | null;
  priceNet: Generated<Numeric>;
  priceNet2: Generated<Numeric | null>;
  priceNet3: Generated<Numeric | null>;
  quantityDiscounts: Generated<Json | null>;
  sortOrder: Generated<number | null>;
  supplier: Generated<string | null>;
  taxRate: Generated<Numeric | null>;
  thumbnailUrl: string | null;
  updatedAt: Generated<Timestamp | null>;
  weight: string | null;
}

export interface PushNotificationLog {
  id: Generated<number>;
  message: string;
  sentAt: Generated<Timestamp | null>;
  sentByAdminId: number | null;
  title: string;
}

export interface Reviews {
  comment: string | null;
  customerId: number | null;
  id: Generated<number>;
  productId: number | null;
  starRating: number;
  submittedAt: Generated<Timestamp | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface SonderbereichFiles {
  active: Generated<boolean | null>;
  description: string | null;
  fileSize: Int8 | null;
  id: Generated<number>;
  pdfUrl: string;
  title: string;
  uploadDate: Generated<Timestamp | null>;
}

export interface Suppliers {
  active: Generated<boolean>;
  address: string | null;
  contactPerson: string | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: Generated<number>;
  name: string;
  notes: string | null;
  phone: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserNotifications {
  createdAt: Generated<Timestamp>;
  dismissed: Generated<boolean>;
  id: Generated<number>;
  message: string;
  title: string;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  active: Generated<boolean | null>;
  avatarUrl: string | null;
  bibercode: string | null;
  billingCity: string | null;
  billingCompanyName: string | null;
  billingCountry: Generated<string | null>;
  billingPostcode: string | null;
  billingStreet: string | null;
  billingTaxNumber: string | null;
  charityOrganizationId: number | null;
  city: string | null;
  companyName: string | null;
  createdAt: Generated<Timestamp | null>;
  dateOfBirth: Timestamp | null;
  deliveryAddressSameAsBilling: Generated<boolean>;
  deliveryCity: string | null;
  deliveryCompanyName: string | null;
  deliveryFirstName: string | null;
  deliveryLastName: string | null;
  deliveryMobileNumber: string | null;
  deliveryPostcode: string | null;
  deliveryStreet: string | null;
  displayName: string;
  dropoffDescription: string | null;
  dropoffPhotoUrl: string | null;
  email: string;
  emailVerified: Generated<boolean | null>;
  firstName: string | null;
  iban: Generated<string | null>;
  id: Generated<number>;
  invoiceCity: string | null;
  invoiceCompanyName: string | null;
  invoiceHouseNumber: string | null;
  invoicePostcode: string | null;
  invoiceStreet: string | null;
  invoiceTaxId: string | null;
  invoiceTaxNumber: string | null;
  languagePreference: Generated<LanguagePreference | null>;
  lastName: string | null;
  mobileNumber: string | null;
  newsletterOptIn: Generated<boolean>;
  notificationPreference: Generated<NotificationPreference | null>;
  packagingCompensation: Generated<Numeric | null>;
  pointsBalance: Generated<Numeric | null>;
  postcode: string | null;
  referredByBibercode: string | null;
  role: Generated<UserRole>;
  salutation: string | null;
  stopCompensation: Generated<Numeric | null>;
  streetAddress: string | null;
  updatedAt: Generated<Timestamp | null>;
  vatEligible: Generated<boolean>;
}

export interface WalletTopups {
  amount: Numeric;
  bonusPercent: Generated<Numeric | null>;
  customerId: number | null;
  id: Generated<number>;
  paymentMethod: PaymentMethodType | null;
  pointsCredited: Numeric;
  topupDate: Generated<Timestamp | null>;
}

export interface ZoneDriverAssignments {
  carType: string | null;
  dateKey: string;
  driverId: number | null;
  id: Generated<number>;
  packer: Generated<string | null>;
  postcode: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  analyticsDaily: AnalyticsDaily;
  analyticsEvents: AnalyticsEvents;
  appSettings: AppSettings;
  charityOrganizations: CharityOrganizations;
  deliveryZones: DeliveryZones;
  driverCreditNotes: DriverCreditNotes;
  driverDeliveryRatings: DriverDeliveryRatings;
  driverTips: DriverTips;
  emailSignatures: EmailSignatures;
  emailTemplates: EmailTemplates;
  loginAttempts: LoginAttempts;
  notificationTemplates: NotificationTemplates;
  oauthAccessToken: OauthAccessToken;
  orderItems: OrderItems;
  orders: Orders;
  passwordResetTokens: PasswordResetTokens;
  pointTransactions: PointTransactions;
  productCategories: ProductCategories;
  productRatings: ProductRatings;
  products: Products;
  pushNotificationLog: PushNotificationLog;
  reviews: Reviews;
  sessions: Sessions;
  sonderbereichFiles: SonderbereichFiles;
  suppliers: Suppliers;
  userNotifications: UserNotifications;
  userPasswords: UserPasswords;
  users: Users;
  walletTopups: WalletTopups;
  zoneDriverAssignments: ZoneDriverAssignments;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","driver","user"];
export const LanguagePreferenceArrayValues: [LanguagePreference, ...LanguagePreference[]] = ["de","en","es","it","tr"];
export const NotificationPreferenceArrayValues: [NotificationPreference, ...NotificationPreference[]] = ["both","email","sms"];
export const OrderStatusArrayValues: [OrderStatus, ...OrderStatus[]] = ["cancelled","confirmed","delivered","delivering","pending"];
export const PaymentMethodTypeArrayValues: [PaymentMethodType, ...PaymentMethodType[]] = ["apple_pay","credit_card","gpay","klarna","paypal","points"];
export const PointTransactionTypeArrayValues: [PointTransactionType, ...PointTransactionType[]] = ["admin_adjustment","bibercode_credit","order_payment","topup"];
export const CreditNoteStatusArrayValues: [CreditNoteStatus, ...CreditNoteStatus[]] = ["approved_auto","approved_manual","pending"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.